# This is a basic workflow to help you get started with Actions

name: Plan

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  terraform-plan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      working_directory: "environments/nonprod/platform"
      aksmodule_directory: "environments/nonprod/platform/modules/aks"
      nwmodule_directory: "environments/nonprod/platform/modules/network"
      k8smodule_directory: "environments/nonprod/platform/modules/k8s"

    # Steps represent a sequence of tasks that will be executed as part of the job
    
    defaults:
      run:
        shell: bash
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run
        run: bash scripts/azlogin.sh
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.1.9"

      - name: Terraform getaks
        run: terraform -chdir=${{ env.aksmodule_directory }} get

      - name: Terraform getnw
        run: terraform -chdir=${{ env.nwmodule_directory }} get  

      - name: Terraform get k8s
        run: terraform -chdir=${{ env.k8smodule_directory }} get   

      - name: Terraform Init
        run: terraform -chdir=${{ env.working_directory }} init

      - name: Terraform Plan
        run: terraform -chdir=${{ env.working_directory }} plan -lock=false


      - name: Terraform Init for k8s
        run: terraform -chdir=${{ env.k8smodule_directory }} init

      - name: Terraform Plan for k8s
        run: terraform -chdir=${{ env.k8smodule_directory }} plan -lock=false  

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
